import Head from 'next/head'
// import { useRouter } from 'next/router'
// import { useState } from 'react'
// import toast from 'react-hot-toast'
import { Header, Hero, Footer, Metrics, Pricing } from '@/components/Landing'
export default function Home() {
  // const router = useRouter()
  // const [eventCode, setEventCode] = useState('')

  // const joinEvent = async () => {
  //   // https://hive-deployment.onrender.com/rooms/e6KW6zMOA
  //   if (!eventCode) {
  //     setEventCode(defaultRoom)
  //   }
  //   if (eventCode) {
  //     toast.loading('Odaya giriş yapılıyor...')
  //     const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/rooms/${eventCode}`, {
  //       method: 'POST',
  //       headers: {
  //         'Content-Type': 'application/json',
  //       },
  //     })
  //     if (res.status === 200) {
  //       const data = await res.json()
  //       toast.dismiss()
  //       toast.success(data.message || 'Odaya giriş yapıldı')
  //       setTimeout(() => {
  //         router.push(`/events/${data.participant.room}`)
  //       }, 300)
  //     }
  //     else {
  //       const err = await res.json()
  //       toast.dismiss()
  //       toast.error(err.message || 'Odaya giriş yapılamadı')
  //     }
  //   }
  // }
  return (
    <>
      <Head>
        <title>Hive Ana Sayfa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className='max-w-[1280px] w-full h-screen mx-auto'
      >
        <Header />
        <Hero />
        <Pricing />
        <Metrics />
        <Footer />
      </main >
    </>
  )
}
